import fs from "node:fs";
import path from "node:path";
import { JURISDICTIONS } from "../src/data/jurisdictions.data";
import { ALL_STATUSES, ALL_REGIONS } from "../src/data/jurisdictions";

const byStatus = Object.fromEntries(ALL_STATUSES.map((s) => [s, 0])) as Record<
  (typeof ALL_STATUSES)[number],
  number
>;
const byRegion = Object.fromEntries(ALL_REGIONS.map((r) => [r, 0])) as Record<string, number>;
let sidsNoLaw = 0;
const byIso3: Record<string, {
  jurisdiction: string;
  region: string;
  lawStatus: string;
  keyLawName: string | null;
  keyLawYear: number | null;
}> = {};

for (const j of JURISDICTIONS) {
  byStatus[j.lawStatus] = (byStatus[j.lawStatus] ?? 0) + 1;
  byRegion[j.region] = (byRegion[j.region] ?? 0) + 1;
  if (j.sids && j.lawStatus === "none") sidsNoLaw++;
  if (j.iso3) {
    byIso3[j.iso3] = {
      jurisdiction: j.jurisdiction,
      region: j.region,
      lawStatus: j.lawStatus,
      keyLawName: j.keyLawName,
      keyLawYear: j.keyLawYear,
    };
  }
}

const pioneerJ = [...JURISDICTIONS]
  .filter((j) => j.firstLawYear)
  .sort((a, b) => (a.firstLawYear ?? 9999) - (b.firstLawYear ?? 9999))[0];
const pioneer = pioneerJ
  ? { jurisdiction: pioneerJ.jurisdiction, firstLawYear: pioneerJ.firstLawYear }
  : null;

const summary = {
  total: JURISDICTIONS.length,
  byStatus,
  byRegion,
  sidsNoLaw,
  pioneer,
  byIso3,
};

const out = `// AUTO-GENERATED by scripts/generate-kpi-summary.ts — do not edit by hand.
import type { LawStatus } from "./jurisdictions";

export interface KpiSummaryEntry {
  jurisdiction: string;
  region: string;
  lawStatus: LawStatus;
  keyLawName: string | null;
  keyLawYear: number | null;
}

export const KPI_SUMMARY: {
  total: number;
  byStatus: Record<LawStatus, number>;
  byRegion: Record<string, number>;
  sidsNoLaw: number;
  byIso3: Record<string, KpiSummaryEntry>;
} = ${JSON.stringify(summary, null, 2)};
`;

const target = path.join(process.cwd(), "src/data/kpiSummary.ts");
fs.writeFileSync(target, out);
console.log(`Wrote ${target} (${out.length} bytes, ${JURISDICTIONS.length} jurisdictions)`);
