// AUTO-GENERATED by scripts/generate-kpi-summary.ts — do not edit by hand.
import type { LawStatus } from "./jurisdictions";

export interface KpiSummaryEntry {
  jurisdiction: string;
  region: string;
  lawStatus: LawStatus;
  keyLawName: string | null;
  keyLawYear: number | null;
}

export const KPI_SUMMARY: {
  total: number;
  byStatus: Record<LawStatus, number>;
  byRegion: Record<string, number>;
  sidsNoLaw: number;
  dpaCount: number;
  pioneerYear: number | null;
  recentYear: number | null;
  pioneer: { jurisdiction: string; firstLawYear: number | null } | null;
  byIso3: Record<string, KpiSummaryEntry>;
} = {
  "total": 252,
  "byStatus": {
    "comprehensive": 172,
    "partial": 6,
    "none": 74
  },
  "byRegion": {
    "Africa": 60,
    "Asia": 54,
    "Europe": 52,
    "Latin America and the Caribbean": 52,
    "Americas": 5,
    "Oceania": 29
  },
  "sidsNoLaw": 33,
  "dpaCount": 171,
  "pioneerYear": 1974,
  "recentYear": 2024,
  "pioneer": {
    "jurisdiction": "Sweden",
    "firstLawYear": 1973
  },
  "byIso3": {
    "AFG": {
      "jurisdiction": "Afghanistan",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "ALA": {
      "jurisdiction": "Åland Is.",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Provincial law on data protection within the provincial and municipal administration ( landskapslag om dataskydd inom landskaps- och kommunalförvaltningen  )",
      "keyLawYear": 2019
    },
    "ALB": {
      "jurisdiction": "Albania",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Act on the Protection of Personal Data (Law No. 9887, Amended by  Law No. 120/2014)",
      "keyLawYear": 2014
    },
    "DZA": {
      "jurisdiction": "Algeria",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 18-07 on protection of individuals in the processing of personal information, updated 2023. Earlier edition 2018. ( Loi n° 18-07 du 25 Ramadhan 1439 correspondant au 10 juin 2018 modifiant et compleétant l’ordonnance relative à la protection des personnes physiques dans le traitement des données à caractère personnel,)",
      "keyLawYear": 2023
    },
    "ASM": {
      "jurisdiction": "American Samoa",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "AND": {
      "jurisdiction": "Andorra",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Qualified Act of personal data protection ( Entrada en vigor de la Llei 29/2021, qualificada de protecció de dades personals  LQPD )",
      "keyLawYear": 2021
    },
    "AGO": {
      "jurisdiction": "Angola",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law ( Lei 22 /11 de 17 Junho —2011 Protecção de Dados Pessoais )",
      "keyLawYear": 2011
    },
    "AIA": {
      "jurisdiction": "Anguilla",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "ATG": {
      "jurisdiction": "Antigua & Barbuda",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 2013, No.10 of 2013",
      "keyLawYear": 2013
    },
    "ARG": {
      "jurisdiction": "Argentina",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law No. 25,326, incl. Executive Order No. 1558/2001 and Supplementary Regulations (PDPL)",
      "keyLawYear": 2018
    },
    "ARM": {
      "jurisdiction": "Armenia",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law of the Republic of Armenia on Protection of Personal Data AB 2011 No. 37, as amended by AB 2021 No. 29",
      "keyLawYear": 2021
    },
    "ABW": {
      "jurisdiction": "Aruba",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "National Ordinance on Personal Registration  AB 2011 no. 37, new amendments most recently in 2021 (AB 2021 No.29)",
      "keyLawYear": 2011
    },
    "AUS": {
      "jurisdiction": "Australia",
      "region": "Oceania",
      "lawStatus": "comprehensive",
      "keyLawName": "Privacy Act 1988. The Privacy Act has undergone a government review as of 2023, which includes potential reforms. https://www.ag.gov.au/rights-and-protections/publications/privacy-act-review-report",
      "keyLawYear": 2022
    },
    "AUT": {
      "jurisdiction": "Austria",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Federal Act concerning the Protection of Personal Data",
      "keyLawYear": 2018
    },
    "AZE": {
      "jurisdiction": "Azerbaijan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 998-IIIQ on Personal Data",
      "keyLawYear": 2010
    },
    "BHS": {
      "jurisdiction": "Bahamas",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act CH.324.A",
      "keyLawYear": 2003
    },
    "BHR": {
      "jurisdiction": "Bahrain",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. (30) of 2018 with Respect to Personal Data Protection Law",
      "keyLawYear": 2022
    },
    "BGD": {
      "jurisdiction": "Bangladesh",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": 2018
    },
    "BRB": {
      "jurisdiction": "Barbados",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act,  2019-29",
      "keyLawYear": 2019
    },
    "BLR": {
      "jurisdiction": "Belarus",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Personal Data Protection 2021",
      "keyLawYear": 2021
    },
    "BEL": {
      "jurisdiction": "Belgium",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on the Protection of Natural Persons with regard to the Processing of Personal Data",
      "keyLawYear": 2018
    },
    "BLZ": {
      "jurisdiction": "Belize",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act No. 45 of 2021",
      "keyLawYear": 2021
    },
    "BEN": {
      "jurisdiction": "Benin",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 2017-20 of April 20, 2018 (Digital Communications and Personal Data Protection)",
      "keyLawYear": 2018
    },
    "BMU": {
      "jurisdiction": "Bermuda",
      "region": "Americas",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Information Protection Act 2016: 43",
      "keyLawYear": 2016
    },
    "BTN": {
      "jurisdiction": "Bhutan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Bhutan Information, Communications and Media Act 2006",
      "keyLawYear": 2018
    },
    "BOL": {
      "jurisdiction": "Bolivia (Plurinational State of)",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "BES": {
      "jurisdiction": "Bonaire, Sint Eustatius & Saba",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act BES",
      "keyLawYear": 2010
    },
    "BIH": {
      "jurisdiction": "Bosnia & Herzegovina",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on the protection of personal data",
      "keyLawYear": 2011
    },
    "BWA": {
      "jurisdiction": "Botswana",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Botswanan Data Protection Act, 2018, No. 32. Effective date is 13 October 2024.",
      "keyLawYear": 2018
    },
    "BVT": {
      "jurisdiction": "Bouvet Island",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "BRA": {
      "jurisdiction": "Brazil",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "General Law for the Protection of Personal Data (LGPD), Law No. 13.709/2018",
      "keyLawYear": 2018
    },
    "IOT": {
      "jurisdiction": "British Indian Ocean Territory",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "VGB": {
      "jurisdiction": "British Virgin Islands",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Virgin Islands Data Protection Act 2021.",
      "keyLawYear": 2021
    },
    "BRN": {
      "jurisdiction": "Brunei Darussalam",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "BGR": {
      "jurisdiction": "Bulgaria",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act",
      "keyLawYear": 2023
    },
    "BFA": {
      "jurisdiction": "Burkina Faso",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 2021 ( Act No. 001-2021)",
      "keyLawYear": 2021
    },
    "BDI": {
      "jurisdiction": "Burundi",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "CPV": {
      "jurisdiction": "Cabo Verde",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Lei No. 120.IX.2021 que proceded a alteraçāo da Lei 42/VIII/2013 - Comissāo Nacional de Protecçāo de Dados CNPD. Ratified Convention 108, Signatory to Con. 108+.",
      "keyLawYear": 2021
    },
    "KHM": {
      "jurisdiction": "Cambodia",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "CMR": {
      "jurisdiction": "Cameroon",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Comprehensive data protection law is not yet in place. However,Cameroon has an active draft bill, [ Draft Bill, 30 May 2023: https://www.minpostel.gov.cm/images/Documentation/patnuc/textes_preparation_pour_consultation_publique/protection_data/230516_Loi Data _FIN_CLEAN.pdf . ] [Draft decree: https://www.minpostel.gov.cm/images/Documentation/patnuc/textes_preparation_pour_consultation_publique/protection_data/230518 Decret_APD FIN _CLEAN.pdf] . Cameroon has signed but not ratified the African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention ) 2021",
      "keyLawYear": null
    },
    "CAN": {
      "jurisdiction": "Canada",
      "region": "Americas",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Information Protection and Electronic Documents Act (private sector); Privacy Act (public sector)",
      "keyLawYear": 2019
    },
    "CYM": {
      "jurisdiction": "Cayman Islands",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Law 2021 (Law 56 of 2020)",
      "keyLawYear": 2021
    },
    "CAF": {
      "jurisdiction": "Central African Republic",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "TCD": {
      "jurisdiction": "Chad",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act No. 007/PR/2015",
      "keyLawYear": 2019
    },
    "CHL": {
      "jurisdiction": "Chile",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 19,628 on Protection of Private Life",
      "keyLawYear": 2020
    },
    "CHN": {
      "jurisdiction": "China",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Information Protection Law",
      "keyLawYear": 2021
    },
    "HKG": {
      "jurisdiction": "China: Hong Kong SAR",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data (Privacy) Ordinance",
      "keyLawYear": 2022
    },
    "MAC": {
      "jurisdiction": "China: Macau SAR",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act",
      "keyLawYear": 2005
    },
    "CXR": {
      "jurisdiction": "Christmas Island",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "CCK": {
      "jurisdiction": "Cocos (Keeling) Islands",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "COL": {
      "jurisdiction": "Colombia",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 2157",
      "keyLawYear": 2021
    },
    "COM": {
      "jurisdiction": "Comoros",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "COG": {
      "jurisdiction": "Congo",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 29-2019 on personal data protection. Has Has signed and ratified the African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention ) 2020.",
      "keyLawYear": 2019
    },
    "COK": {
      "jurisdiction": "Cook Islands",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "CRI": {
      "jurisdiction": "Costa Rica",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 7975, Undisclosed Information Law, and Law No. 8968, Protection in the Handling of the Personal Data of Individuals",
      "keyLawYear": 2016
    },
    "CIV": {
      "jurisdiction": "Côte d'Ivoire",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 2013-450 relating to the protection of Personal Data",
      "keyLawYear": 2013
    },
    "HRV": {
      "jurisdiction": "Croatia",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on the Implementation of the General Regulation on Data Protection",
      "keyLawYear": 2018
    },
    "CUB": {
      "jurisdiction": "Cuba",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 149/2022 De Pretección do Datos Personales (Personal Data Protection)",
      "keyLawYear": null
    },
    "CUW": {
      "jurisdiction": "Curaçao",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Privacy Act Curaçao, 2013",
      "keyLawYear": 2013
    },
    "CYP": {
      "jurisdiction": "Cyprus",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 125(I)2018 Law providing for the Protection of Natural Persons with regard to the Processing of Personal Data and for the Free Movement of such data of 2018",
      "keyLawYear": 2018
    },
    "CZE": {
      "jurisdiction": "Czechia",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Processing Act of 2019 (Implements GDPR)",
      "keyLawYear": 2019
    },
    "PRK": {
      "jurisdiction": "Democratic People’s Republic of Korea",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "COD": {
      "jurisdiction": "Democratic Republic of the Congo",
      "region": "Africa",
      "lawStatus": "partial",
      "keyLawName": "On 4 April 2023 DRC Ministry of Digital ratified the African Union  Convention on Cybersecurity and Personal Data protection (Malabo Convention.) via Ordinance Law No. 23/010 of 13 March 2023, which also authorized (The Digital Code). [Sectoral] Law on Telecommunications, Information and Communication Technology No. 20/017.",
      "keyLawYear": 2023
    },
    "DNK": {
      "jurisdiction": "Denmark",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act",
      "keyLawYear": 2018
    },
    "DJI": {
      "jurisdiction": "Djibouti",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Comprehensive data protection is not in place, however, Djibouti has signed but not yet ratified the African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention ) 2023",
      "keyLawYear": null
    },
    "DMA": {
      "jurisdiction": "Dominica",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 172-13 on the Comprehensive Protection of Personal Data",
      "keyLawYear": 2013
    },
    "DOM": {
      "jurisdiction": "Dominican Republic",
      "region": "Latin America and the Caribbean",
      "lawStatus": "partial",
      "keyLawName": "Ley No. 172-13 sobre Protección de Datas de Carácter Personal del 13 de diciembre de 2013. This is a data protection law, but it is not comprehensive.",
      "keyLawYear": null
    },
    "ECU": {
      "jurisdiction": "Ecuador",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Organic Law on the Protection of Personal Data 2021",
      "keyLawYear": 2021
    },
    "EGY": {
      "jurisdiction": "Egypt",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law, Law No. 151 of 2020.",
      "keyLawYear": 2020
    },
    "SLV": {
      "jurisdiction": "El Salvador",
      "region": "Latin America and the Caribbean",
      "lawStatus": "partial",
      "keyLawName": "[Sectoral] Ley de Protección de Datos Personales y Habeas Data (2019) protects some aspects of data but it is not a comprehensive regulation.",
      "keyLawYear": null
    },
    "GNQ": {
      "jurisdiction": "Equatorial Guinea",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law, Ley Núm. 1/2016",
      "keyLawYear": 2016
    },
    "ERI": {
      "jurisdiction": "Eritrea",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "EST": {
      "jurisdiction": "Estonia",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act",
      "keyLawYear": 2018
    },
    "SWZ": {
      "jurisdiction": "Eswatini",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "The Data Protection Act  No. 5 of 2022",
      "keyLawYear": null
    },
    "ETH": {
      "jurisdiction": "Ethiopia",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "FDRE Personal Data Protection Proclamation No. 1321/2024",
      "keyLawYear": null
    },
    "FLK": {
      "jurisdiction": "Falkland Islands (Malvinas)",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "FRO": {
      "jurisdiction": "Faroe Islands",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act",
      "keyLawYear": 2020
    },
    "FJI": {
      "jurisdiction": "Fiji",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "FIN": {
      "jurisdiction": "Finland",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act (supplements GDPR)",
      "keyLawYear": 2018
    },
    "FRA": {
      "jurisdiction": "France",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 2018-493 relating to the protection of personal data and amending Law No. 78-17",
      "keyLawYear": 2018
    },
    "GUF": {
      "jurisdiction": "French Guiana",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "PYF": {
      "jurisdiction": "French Polynesia",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "ATF": {
      "jurisdiction": "French Southern Territories",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "GAB": {
      "jurisdiction": "Gabon",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 001/2011 on the Protection of Personal Data",
      "keyLawYear": 2011
    },
    "GMB": {
      "jurisdiction": "Gambia",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Gambia is an ECOWAS member and is party to the Supplementary Act on Personal Data Protection within ECOWAS https://ictpolicyafrica.org/en/document/z69cbq7b51?page=1 . Gambia has signed but not ratified the African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention ) as of 2022. There is a 2021 draft bill and a 2019 Data Protection and Privacy Strategy. https://gmcsirt.gm/wp-content/uploads/2021/12/Data-Protection-and-Privacy-Policy-and-Strategy-August-2019-Final.pdf. The",
      "keyLawYear": null
    },
    "GEO": {
      "jurisdiction": "Georgia",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Personal Data Protection",
      "keyLawYear": 2012
    },
    "DEU": {
      "jurisdiction": "Germany",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Federal Data Protection Act",
      "keyLawYear": 2021
    },
    "GHA": {
      "jurisdiction": "Ghana",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act  (Act No. 843) 2012",
      "keyLawYear": 2012
    },
    "GIB": {
      "jurisdiction": "Gibraltar",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act",
      "keyLawYear": 2004
    },
    "GRC": {
      "jurisdiction": "Greece",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 4624/2019 Protection of Personal Data and Measures for Implementation of GDPR",
      "keyLawYear": 2019
    },
    "GRL": {
      "jurisdiction": "Greenland",
      "region": "Americas",
      "lawStatus": "comprehensive",
      "keyLawName": "The Data Protection Act",
      "keyLawYear": 2018
    },
    "GRD": {
      "jurisdiction": "Grenada",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "GLP": {
      "jurisdiction": "Guadeloupe",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "GUM": {
      "jurisdiction": "Guam",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "GTM": {
      "jurisdiction": "Guatemala",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "[Draft bill Personal Data Protection Law 2022] Otherwise limited protection, for example, Numero 4090 …. Ley de Protección de Datos Personales",
      "keyLawYear": null
    },
    "GGY": {
      "jurisdiction": "Guernsey",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection (Bailiwick of Guernsey) Law",
      "keyLawYear": 2017
    },
    "GIN": {
      "jurisdiction": "Guinea",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Cybersecurity and Personal Data. 2016.  Also, has ratified the African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention ) 2018.  Guinea is also a Party to the Supplementary Act on Personal Data Protection within ECOWAS https://ictpolicyafrica.org/en/document/z69cbq7b51?page=1",
      "keyLawYear": 2016
    },
    "GNB": {
      "jurisdiction": "Guinea-Bissau",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Has signed but not ratified the African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention ) 2015. Is also an Ecowas member and party to the Supplementary Act on Personal Data Protection within ECOWAS https://ictpolicyafrica.org/en/document/z69cbq7b51?page=1",
      "keyLawYear": null
    },
    "GUY": {
      "jurisdiction": "Guyana",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "HTI": {
      "jurisdiction": "Haiti",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "HMD": {
      "jurisdiction": "Heard Island and McDonald Islands",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "VAT": {
      "jurisdiction": "Holy See",
      "region": "Europe",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "HND": {
      "jurisdiction": "Honduras",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "HUN": {
      "jurisdiction": "Hungary",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Act on Informational Self-Determination and Freedom of Information",
      "keyLawYear": 2018
    },
    "ISL": {
      "jurisdiction": "Iceland",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 90/2018 Act on Data Protection and the Processing of Personal Data (implementing GDPR)",
      "keyLawYear": 2018
    },
    "IND": {
      "jurisdiction": "India",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Digital Personal Data Protection Bill 2023 (DPDP Act)",
      "keyLawYear": 2000
    },
    "IDN": {
      "jurisdiction": "Indonesia",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law; Undang-Udang Republik Indonesia Nomor 27 Tahum 2022 Tentang Pelindungan Data Pribadi",
      "keyLawYear": 2022
    },
    "IRN": {
      "jurisdiction": "Iran (Islamic Republic of)",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "IRQ": {
      "jurisdiction": "Iraq",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "IRL": {
      "jurisdiction": "Ireland",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act",
      "keyLawYear": 2022
    },
    "IMN": {
      "jurisdiction": "Isle of Man",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 2018 (Application of the GDPR)",
      "keyLawYear": 2018
    },
    "ISR": {
      "jurisdiction": "Israel",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Privacy Protection Law /57411981 and 5752/1992",
      "keyLawYear": 1996
    },
    "ITA": {
      "jurisdiction": "Italy",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Code (Legislative Decree 101/2018 harmoizes with GDPR)",
      "keyLawYear": 2018
    },
    "JAM": {
      "jurisdiction": "Jamaica",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 2020",
      "keyLawYear": 2020
    },
    "JPN": {
      "jurisdiction": "Japan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Act on the Protection of Personal Information (APPI)",
      "keyLawYear": 2020
    },
    "JEY": {
      "jurisdiction": "Jersey",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection (Jersey) Law 2018",
      "keyLawYear": 2018
    },
    "JOR": {
      "jurisdiction": "Jordan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law No. 24 of 2023",
      "keyLawYear": null
    },
    "KAZ": {
      "jurisdiction": "Kazakhstan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Personal Data and Their Protection",
      "keyLawYear": 2020
    },
    "KEN": {
      "jurisdiction": "Kenya",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act, 2019",
      "keyLawYear": 2019
    },
    "KIR": {
      "jurisdiction": "Kiribati",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "UNK": {
      "jurisdiction": "Kosovo*",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 06/L-082 on the Protection of Personal Data",
      "keyLawYear": 2019
    },
    "KWT": {
      "jurisdiction": "Kuwait",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Privacy Protection Regulation 2021, User Protection and Privacy Rules Regulation 2021, Resolution No. 42 - On Data Privacy Protection Regulation 2022.",
      "keyLawYear": null
    },
    "KGZ": {
      "jurisdiction": "Kyrgyzstan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Personal Data",
      "keyLawYear": 2021
    },
    "LAO": {
      "jurisdiction": "Lao People’s Dem. Republic",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Electronic Data Protection Act 2017",
      "keyLawYear": 2018
    },
    "LVA": {
      "jurisdiction": "Latvia",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "The Law on the Processing of Personal Data",
      "keyLawYear": 2021
    },
    "LBN": {
      "jurisdiction": "Lebanon",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 81 Relating to Electronic Transactions and Personal Data",
      "keyLawYear": 2018
    },
    "LSO": {
      "jurisdiction": "Lesotho",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 2012",
      "keyLawYear": 2013
    },
    "LBR": {
      "jurisdiction": "Liberia",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Comprehensive data protection law has not been passed. However, Liberia is a member of ECOWAS and a party to the Supplementary Act on Personal Data Protection within ECOWAS https://ictpolicyafrica.org/en/document/z69cbq7b51?page=1. Liberia is a member of the AU.",
      "keyLawYear": null
    },
    "LBY": {
      "jurisdiction": "Libya",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "LIE": {
      "jurisdiction": "Liechtenstein",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act (implements GDPR)",
      "keyLawYear": 2018
    },
    "LTU": {
      "jurisdiction": "Lithuania",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Legal Protection of Personal Data (Implements GDPR)",
      "keyLawYear": 2018
    },
    "LUX": {
      "jurisdiction": "Luxembourg",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Law (implementes GDPR)",
      "keyLawYear": 2018
    },
    "MDG": {
      "jurisdiction": "Madagascar",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 2014 - 038 On the protection of personal data",
      "keyLawYear": 2014
    },
    "MWI": {
      "jurisdiction": "Malawi",
      "region": "Africa",
      "lawStatus": "partial",
      "keyLawName": "Comprehensive data protection is not yet in place, however there is an active draft: [Draft comprehensive bill published, Data Protection Bill 2023. ] Additionally, there is Sectoral coverage: Electronic Transactions and Cyber Security Act, 2016. Malawi is a member of the AU.",
      "keyLawYear": 2016
    },
    "MYS": {
      "jurisdiction": "Malaysia",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act 2010 (PDP)",
      "keyLawYear": 2010
    },
    "MDV": {
      "jurisdiction": "Maldives",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "MLI": {
      "jurisdiction": "Mali",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law n ° 2013-015 on the Protection of Personal Data in the Republic of Mali",
      "keyLawYear": 2013
    },
    "MLT": {
      "jurisdiction": "Malta",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act",
      "keyLawYear": 2021
    },
    "MHL": {
      "jurisdiction": "Marshall Islands",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "MTQ": {
      "jurisdiction": "Martinique",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "MRT": {
      "jurisdiction": "Mauritania",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 2017-020 on Personal Data Protection. Also, Mauritania has ratified the Malabo Convention.",
      "keyLawYear": 2011
    },
    "MUS": {
      "jurisdiction": "Mauritius",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act, 2017. Mauritius has also ratified the Malabo Convention as well as Convention 108 and 108+.",
      "keyLawYear": 2017
    },
    "MYT": {
      "jurisdiction": "Mayotte",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "MEX": {
      "jurisdiction": "Mexico",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Federal Law on Protection of Personal Data Held by Private Parties (LFPDPPP) - Private Sector.  General Law for the Protection of Personal Data in Possession of Obligated Parties (LGPDPPSO) - Public Sector. Mexico has ratified Convention 108.",
      "keyLawYear": 2017
    },
    "FSM": {
      "jurisdiction": "Micronesia  (Federated States of)",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "MCO": {
      "jurisdiction": "Monaco",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Act no. 1.353 modifying the Act no. 1.165 on personal data protection",
      "keyLawYear": 2008
    },
    "MNG": {
      "jurisdiction": "Mongolia",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Protection of Personal Information 2021",
      "keyLawYear": 2021
    },
    "MNE": {
      "jurisdiction": "Montenegro",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law",
      "keyLawYear": 2017
    },
    "MSR": {
      "jurisdiction": "Montserrat",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "MAR": {
      "jurisdiction": "Morocco",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 09-08 on the Protection of Individuals with Regard to the Processing of Personal Data, 2009. Signed and ratified Convention 108.",
      "keyLawYear": 2009
    },
    "MOZ": {
      "jurisdiction": "Mozambique",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Mozambique has an active draft law: [Draft law: Mozambique Data Protection Act 2024 ] Mozambique has also signed and ratified the African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention ) 2020",
      "keyLawYear": null
    },
    "MMR": {
      "jurisdiction": "Myanmar",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "NAM": {
      "jurisdiction": "Namibia",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Namibia ratified the Malabo Convention in 2019. Namibia has published a Draft Data Protection bill. https://dataprotection.africa/wp-content/uploads/2022/09/Namibia_DPA-Bill.pdf",
      "keyLawYear": null
    },
    "NRU": {
      "jurisdiction": "Nauru",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "NPL": {
      "jurisdiction": "Nepal",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "The Privacy Act, 2075",
      "keyLawYear": 2018
    },
    "NLD": {
      "jurisdiction": "Netherlands",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act (Implements GDPR)",
      "keyLawYear": 2018
    },
    "NCL": {
      "jurisdiction": "New Caledonia",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "NZL": {
      "jurisdiction": "New Zealand",
      "region": "Oceania",
      "lawStatus": "comprehensive",
      "keyLawName": "Privacy Act 2020",
      "keyLawYear": 2020
    },
    "NIC": {
      "jurisdiction": "Nicaragua",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No 787 Personal Data Protection",
      "keyLawYear": 2012
    },
    "NER": {
      "jurisdiction": "Niger",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 2017-28 on the Protection of Personal Data",
      "keyLawYear": 2020
    },
    "NGA": {
      "jurisdiction": "Nigeria",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Nigeria Data Protection Act 2023 (NDPA), Nigerian Data Protection Regulation 2019. (NDPR) Note: Both are in effect. NDPA takes precedence over the NDPR. Certain NDPR Implementation Framework provisions continue to be operative, as long as they do not conflict with NDPA.",
      "keyLawYear": 2020
    },
    "NIU": {
      "jurisdiction": "Niue",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "NFK": {
      "jurisdiction": "Norfolk Island",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "MKD": {
      "jurisdiction": "North Macedonia",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Personal Data Protection",
      "keyLawYear": 2021
    },
    "MNP": {
      "jurisdiction": "Northern Mariana Islands",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "NOR": {
      "jurisdiction": "Norway",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Act on Processing Personal Data",
      "keyLawYear": 2021
    },
    "OMN": {
      "jurisdiction": "Oman",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law 2022",
      "keyLawYear": 2022
    },
    "PAK": {
      "jurisdiction": "Pakistan",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "PLW": {
      "jurisdiction": "Palau",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "PSE": {
      "jurisdiction": "Palestine",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "PAN": {
      "jurisdiction": "Panama",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 81 on Protection of Personal Data",
      "keyLawYear": 2019
    },
    "PNG": {
      "jurisdiction": "Papua New Guinea",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "PRY": {
      "jurisdiction": "Paraguay",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 6534 Protection of Personal Credit Data",
      "keyLawYear": 2020
    },
    "PER": {
      "jurisdiction": "Peru",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 29733 Personal Data Protection Law",
      "keyLawYear": 2017
    },
    "PHL": {
      "jurisdiction": "Philippines",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Republic Act 10173 – Data Privacy Act of 2012 and Implementing Rules and Regulations (Philippine Privacy Laws)",
      "keyLawYear": 2012
    },
    "PCN": {
      "jurisdiction": "Pitcairn",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "POL": {
      "jurisdiction": "Poland",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "The Personal Data Protection Act (Implements GDPR)",
      "keyLawYear": 2018
    },
    "PRT": {
      "jurisdiction": "Portugal",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law No. 58 (Implements GDPR)",
      "keyLawYear": 2019
    },
    "PRI": {
      "jurisdiction": "Puerto Rico",
      "region": "Latin America and the Caribbean",
      "lawStatus": "partial",
      "keyLawName": "Puerto Rico Data Protection Act (Law 52 of 2018). The Consumer Data and Personal Information Protection Act, House Bill No. 1548 was proposed in 2023 to update the 2018 bill. [Sectoral] Some protections under Regla 7(B)1, 20, and 13(A), which provide protection against fraud and unfair and deceptive acts and practices.",
      "keyLawYear": null
    },
    "QAT": {
      "jurisdiction": "Qatar",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "QFC Data Protection Regulations",
      "keyLawYear": 2021
    },
    "KOR": {
      "jurisdiction": "Republic of Korea",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Information Protection Act 2011 (expanding older Acts)",
      "keyLawYear": 2020
    },
    "MDA": {
      "jurisdiction": "Republic of Moldova",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No.133 on Personal Data Protection",
      "keyLawYear": 2021
    },
    "REU": {
      "jurisdiction": "Réunion",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "ROU": {
      "jurisdiction": "Romania",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Federal Law Regarding Personal Data",
      "keyLawYear": 2018
    },
    "RUS": {
      "jurisdiction": "Russian Federation",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Federal Law of 26.07.2006, No. 52-FZ On personal data",
      "keyLawYear": 2014
    },
    "RWA": {
      "jurisdiction": "Rwanda",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 058/2021 Relating to the Protection of Personal Data and Privacy",
      "keyLawYear": 2021
    },
    "BLM": {
      "jurisdiction": "Saint Barthélemy",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "SHN": {
      "jurisdiction": "Saint Helena",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "KNA": {
      "jurisdiction": "Saint Kitts & Nevis",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act, 5 of 2018",
      "keyLawYear": 2018
    },
    "LCA": {
      "jurisdiction": "Saint Lucia",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection (Amendment ) Act No 2 of 2015",
      "keyLawYear": 2015
    },
    "MAF": {
      "jurisdiction": "Saint Martin (French Part)",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "SPM": {
      "jurisdiction": "Saint Pierre and Miquelon",
      "region": "Americas",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "VCT": {
      "jurisdiction": "Saint Vincent  and the Grenadines",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Privacy Act, No. 18 of 2003",
      "keyLawYear": 2003
    },
    "WSM": {
      "jurisdiction": "Samoa",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "SMR": {
      "jurisdiction": "San Marino",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law n. 70: Act on Collection, Elaboration and Use of Computerised Personal Data (reforming Law n. 27 of 1 March 1983). Ratified Convention 108.",
      "keyLawYear": 2019
    },
    "STP": {
      "jurisdiction": "São Tomé and Principe",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 03/X/2.a/2015 – Protection of Personal Data.",
      "keyLawYear": 2015
    },
    "SAU": {
      "jurisdiction": "Saudi Arabia",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law 14 September 2023 (PDPL) and Implementing Regulation.",
      "keyLawYear": 2021
    },
    "SEN": {
      "jurisdiction": "Senegal",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law N 2008- 12 Concerning Personal Data Protection. Signed and ratified Convention 108.",
      "keyLawYear": 2008
    },
    "SRB": {
      "jurisdiction": "Serbia",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "The Law on the Protection of Personal Data. Also Ratified Convention 108.",
      "keyLawYear": 2018
    },
    "SYC": {
      "jurisdiction": "Seychelles",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 2023. Data Protection Act 2003 repealed and replaced by 2023 Act.",
      "keyLawYear": 2003
    },
    "SLE": {
      "jurisdiction": "Sierra Leone",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Sierra Leone is a member of ECOWAS and a party to the Supplementary Act on Personal Data Protection within ECOWAS https://ictpolicyafrica.org/en/document/z69cbq7b51?page=1. Sierra Leone has signed but not ratified Malabo Convention. Does not appear to have passed national comprehensive data privacy legislation beyond this.",
      "keyLawYear": null
    },
    "SGP": {
      "jurisdiction": "Singapore",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act 2012 (PDPA)",
      "keyLawYear": 2020
    },
    "SXM": {
      "jurisdiction": "Sint Maarten  (Dutch Part)",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "National ordinance personal data protection (Landsverordening bescherming persoonsgegevens)",
      "keyLawYear": 2010
    },
    "SVK": {
      "jurisdiction": "Slovakia",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act (Implements GDPR)",
      "keyLawYear": 2018
    },
    "SVN": {
      "jurisdiction": "Slovenia",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act (ZVOP-2) (Implements GDPR)",
      "keyLawYear": 2022
    },
    "SLB": {
      "jurisdiction": "Solomon Islands",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "SOM": {
      "jurisdiction": "Somalia",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 005 of 2023, Data Protection Act known as Somali Data Protection Law (DPL) 2023.",
      "keyLawYear": null
    },
    "ZAF": {
      "jurisdiction": "South Africa",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Protection of Personal Information Act (PoPIA) 2013",
      "keyLawYear": 2013
    },
    "SGS": {
      "jurisdiction": "South Georgia and South Sandwich Islands",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "SSD": {
      "jurisdiction": "South Sudan",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "ESP": {
      "jurisdiction": "Spain",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law 3/2018 Protection of Personal Data and guarantee of digital rights (Implements GDPR)",
      "keyLawYear": 2018
    },
    "LKA": {
      "jurisdiction": "Sri Lanka",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act, No. 9 of 2022",
      "keyLawYear": 2022
    },
    "SDN": {
      "jurisdiction": "Sudan",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "SUR": {
      "jurisdiction": "Suriname",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "SJM": {
      "jurisdiction": "Svalbard and Jan Mayen Islands",
      "region": "Europe",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "SWE": {
      "jurisdiction": "Sweden",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Act 2018:218 (Implements GDPR)",
      "keyLawYear": 2018
    },
    "CHE": {
      "jurisdiction": "Switzerland",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Federal Act on Data Protection (Aligns with GDPR and Convention 108+)",
      "keyLawYear": 2020
    },
    "SYR": {
      "jurisdiction": "Syrian Arab Republic",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 12 of 2024 Regarding the Protection of Electronic Personal Data. The law establishes a data protection authority. Effective date January 2025.",
      "keyLawYear": null
    },
    "TWN": {
      "jurisdiction": "Taiwan*",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act (PDPA) and the Enforcement Rules of the PDPA",
      "keyLawYear": 2016
    },
    "TJK": {
      "jurisdiction": "Tajikistan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on the Protection of Personal Information",
      "keyLawYear": 2018
    },
    "THA": {
      "jurisdiction": "Thailand",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act 2019",
      "keyLawYear": 2021
    },
    "TLS": {
      "jurisdiction": "Timor-Leste",
      "region": "Asia",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "TGO": {
      "jurisdiction": "Togo",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 2019-014 Relating to the Protection of Personal Data",
      "keyLawYear": 2019
    },
    "TKL": {
      "jurisdiction": "Tokelau",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "TON": {
      "jurisdiction": "Tonga",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "TTO": {
      "jurisdiction": "Trinidad & Tobago",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 2011",
      "keyLawYear": 2011
    },
    "TUN": {
      "jurisdiction": "Tunisia",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 2004-63 Relating to the Protection of Personal Data. Signed and ratified Convention 108.",
      "keyLawYear": 2004
    },
    "TUR": {
      "jurisdiction": "Türkiye",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Law. Ratified Convention 108.",
      "keyLawYear": 2016
    },
    "TKM": {
      "jurisdiction": "Turkmenistan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Information on Private Life and its Protection No. 519-V",
      "keyLawYear": 2017
    },
    "TCA": {
      "jurisdiction": "Turks and Caicos Islands",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "TUV": {
      "jurisdiction": "Tuvalu",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "UGA": {
      "jurisdiction": "Uganda",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "The Data Protection and Privacy Act 2019",
      "keyLawYear": 2019
    },
    "UKR": {
      "jurisdiction": "Ukraine",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 2297-VI on Personal Data Protection. Ratified Convention 108.",
      "keyLawYear": 2020
    },
    "ARE": {
      "jurisdiction": "United Arab Emirates: Dubai IFC",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Law No. 5 of 2020",
      "keyLawYear": 2020
    },
    "GBR": {
      "jurisdiction": "United Kingdom of Great Britain and Northern Ireland",
      "region": "Europe",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 2018",
      "keyLawYear": 2018
    },
    "TZA": {
      "jurisdiction": "United Rep. of Tanzania",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Personal Data Protection Act 2022, Act No. 11 of 2022.",
      "keyLawYear": 2022
    },
    "UMI": {
      "jurisdiction": "United States Minor Outlying Islands",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "USA": {
      "jurisdiction": "United States of America",
      "region": "Americas",
      "lawStatus": "partial",
      "keyLawName": "Public sector comprehensive data protection law in place, Privacy Act of 1974. Multiple private sector, Federal, sectoral privacy laws in place: (Financial FCRA, Health HIPAA, GINA; Education FERPA,). Draft comprehensive privacy bill, [Draft: American Privacy Righs Act of 2024, APRA, introduced in 2024] The U.S. has been granted EU adequacy under the EU-US Data Privacy Framework as of 2023.",
      "keyLawYear": 1974
    },
    "VIR": {
      "jurisdiction": "United States Virgin Islands",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "URY": {
      "jurisdiction": "Uruguay",
      "region": "Latin America and the Caribbean",
      "lawStatus": "comprehensive",
      "keyLawName": "Law No. 18331 Personal Data Protection Law. Signed and ratified Convention 108.",
      "keyLawYear": 2022
    },
    "UZB": {
      "jurisdiction": "Uzbekistan",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Personal Data",
      "keyLawYear": 2019
    },
    "VUT": {
      "jurisdiction": "Vanuatu",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "VEN": {
      "jurisdiction": "Venezuela",
      "region": "Latin America and the Caribbean",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "VNM": {
      "jurisdiction": "Viet Nam",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law on Protection of Consumers' Rights and Resolution No. 13 /NQ-CP Regarding Approval for Documents on Protection of Personal Data Protection",
      "keyLawYear": 2023
    },
    "WLF": {
      "jurisdiction": "Wallis and Futuna Islands",
      "region": "Oceania",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "ESH": {
      "jurisdiction": "Western Sahara*",
      "region": "Africa",
      "lawStatus": "none",
      "keyLawName": null,
      "keyLawYear": null
    },
    "YEM": {
      "jurisdiction": "Yemen",
      "region": "Asia",
      "lawStatus": "comprehensive",
      "keyLawName": "Law of the Right of Access to Information",
      "keyLawYear": 2012
    },
    "ZMB": {
      "jurisdiction": "Zambia",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "The Data Protection Act, 2021",
      "keyLawYear": 2021
    },
    "ZWE": {
      "jurisdiction": "Zimbabwe",
      "region": "Africa",
      "lawStatus": "comprehensive",
      "keyLawName": "Data Protection Act 05/ 2021",
      "keyLawYear": 2021
    }
  }
};
